version: "3.8"
services:
  hrcore-fe:
    container_name: hrcore-fe
    stdin_open: true
    tty: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5500:5500"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - repos_external_network
networks:
  repos_external_network:
    external: true
