version: "3.8"
services:
  hrcore-fe:
    container_name: hrcore-fe
    stdin_open: true
    tty: true
    build: .
    ports:
      - "5500:5500"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
