export let userProfile = {
  first_name: 'First Name',
  last_name: 'Last Name',
  middle_name: 'Heart',
  personal_email: 'ojadeson@gmail.com',
  email: 'ojadeson@gmail.com',
  department: 'Accounts',
  profile_image: '',
  dob: '1990-10-20',
  designation: 'Clerk',
  origin_state: 'Lagos',
  employee_id: 'ICS12345',
  role: 'Manager',
  grade: 'G9',
  position: 'P8',
  branch: 'Fadeyi',
  pension: 'xxxxx',
  pension_number: '9434',
  gender: 'male',
  marital_status: 'single',
  lga: 'Mainland',
  residence: 'Obanikoro',
  education: [
    {
      institution: 'University of Lagos',
      award: 'BSc. Engineering',
      year_completed: '2008',
    },
    {
      institution: 'University of Kenturky',
      award: 'Msc. Robotics',
      year_completed: '2010',
    },
  ],
  experience: [
    {
      organization: 'Cubic Consults',
      role: 'Clerk',
      started: '2005-05-02',
      ended: '2007-02-10',
    },
  ],
  hmo: {
    provider: 'Adex',
    hmo_id: 'AD/101',
    hospital: 'Plaza Cross',
    status: 'active',
    plan: 'xxx',
  },
};
